// views/AboutMe.vue
<template>
  <section v-if="aboutMe.length" id="o_mnie" class="aboutMe">
    <h2 class="sectionHeader">O mnie</h2>
    <div class="aboutMe__wrapper">
      <img
        v-if="aboutMePicture.length"
        :src="aboutMePicture[0].image"
        alt="Moje zdjęcie profilowe"
        class="aboutMe__image" />
    </div>
    <div class="aboutMe__categories">
      <button
        v-for="category in aboutMe"
        :key="category.sort"
        :aria-label="'Wyświetl treść kategorii - ' + category.title"
        :class="{ active: active === category.sort }"
        class="aboutMe__category"
        @click="active = category.sort">
        {{ category.title }}
      </button>
    </div>
    <transition mode="out-in" name="shrink">
      <p v-if="selectedDescription" :key="selectedDescription.sort" class="aboutMe__description">
        {{ selectedDescription.description }}
      </p>
    </transition>
  </section>
</template>

<script>
export default {
  name: "AboutMe",
  props: {
    aboutMe: {
      type: Array,
      required: true,
    },
    aboutMePicture: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      active: 1,
    };
  },
  computed: {
    selectedDescription() {
      if (this.aboutMe.length && this.active) return this.aboutMe.find((item) => item.sort === this.active);
      return {};
    },
  },
  mounted() {
    this.active = this.aboutMe?.[0]?.sort;
  },
};
</script>

// views/about-me.tsx
import profilePicture from "assets/images/profile.webp";
import aboutMe from "content/about-me.json";
import Image from "next/image";
import React from "react";

console.log("aboutMe: ", aboutMe);
const title = "test";

const AboutMe = () => {
  return (
    <section id="o_mnie" className="aboutMe">
      <button className="button">Test</button>
      <h2 className="section-header">O mnie</h2>
      <div className="aboutMe__wrapper">
        <Image src={profilePicture} alt="Moje zdjęcie profilowe" className="aboutMe__image" />
      </div>
      <div className="aboutMe__categories">
        <button
          v-for="category in aboutMe"
          key="category.sort"
          aria-label="'Wyświetl treść kategorii - ' + category.title"
          // className="{ active: active === category.sort }"
          className="aboutMe__category"
          onClick={() => console.log("test")}>
          {title}
        </button>
      </div>
      {/*<p key="selectedDescription.sort" className="aboutMe__description">*/}
      {/*  {selectedDescription.description}*/}
      {/*</p>*/}
    </section>
  );
};

export default AboutMe;
