// src/views/Contact.vue
<template>
  <section v-if="contact.length" id="kontakt" class="contact">
    <h2 class="sectionHeader">Kontakt</h2>
    <p class="contact__description" v-html="contact[0].node.description"></p>
    <div class="contact__button">
      <a
        aria-label="Wyślij e-maila na adres jakub.soboczynski@icloud.com"
        class="button"
        href="mailto:jakub.soboczynski@icloud.com"
        rel="noreferrer nofollow noopener"
        target="_blank">
        Cześć
      </a>
    </div>
  </section>
</template>

<script>
export default {
  name: "Contact",
  props: {
    contact: Array,
  },
};
</script>

<style lang="scss" scoped>
.contact {
  padding: 100px 0 clamp(3.75rem, 2.83536586rem + 3.902439vw, 6.25rem);

  &__description {
    max-width: 700px;
    text-align: center;
    font-size: 18px;
    line-height: 24px;
    font-weight: 200;
    margin: 0 auto 30px;
  }

  &__button {
    @include flex-center;
  }
}
</style>

// views/contact.tsx
import React from "react";
import contacts from "content/contacts.json";

const Contact = () => {
  return (
    <section id="kontakt" className="p-contact">
      <h2 className="section-header">Kontakt</h2>
      <p className="font-light text-lg mx-auto mt-0 mb-8 text-center max-w-[700px]">{contacts[0].description}</p>
      <div className="flex-center">
        <a
          aria-label="Wyślij e-maila na adres jakub.soboczynski@icloud.com"
          className="button"
          href="mailto:jakub.soboczynski@icloud.com"
          rel="noreferrer nofollow noopener"
          target="_blank">
          Cześć
        </a>
      </div>
    </section>
  );
};

export default Contact;
