// views/Projects.vue
<template>
  <section v-if="projects.length" id="projekty" class="projects">
    <h2 class="sectionHeader">Projekty</h2>
    <ProjectCard v-for="project in projects" :key="project.sort" :project="project" />
  </section>
</template>

<script>
import ProjectCard from "~/components/ProjectCard.vue";

export default {
  name: "Projects",
  components: {
    ProjectCard,
  },
  props: {
    projects: {
      type: Array,
      required: true,
    },
  },
};
</script>

// views/projects.tsx
import ProjectCard from "components/project-card";
import projects from "content/projects.json";

const Projects = () => {
  return (
    <section id="projekty" className="pb-24">
      <h2 className="section-header">Projekty</h2>
      {projects
        .sort((a, b) => b.id - a.id)
        .map((project) => (
          <ProjectCard key={project.id} {...project} />
        ))}
    </section>
  );
};

export default Projects;
