// src/views/Projects.vue
<template>
  <section v-if="projects.length" id="projekty" class="projects">
    <h2 class="sectionHeader">Projekty</h2>
    <ProjectCard v-for="project in projects" :key="project.node.id" :project="project.node" />
  </section>
</template>

<script>
import ProjectCard from '~/components/ProjectCard.vue';

export default {
  name: 'Projects',
  props: {
    projects: Array,
  },
  components: {
    ProjectCard,
  },
};
</script>

<style lang="scss" scoped>
.projects {
  padding: 100px 0;
}
</style>

// views/projects.tsx
import ProjectCard from "components/project-card";
import projects from "content/projects.json";
import React from "react";

const Projects = () => {
  return (
    <section id="projekty" className="projects">
      <h2 className="section-header">Projekty</h2>
      {projects.map((project) => (
        <ProjectCard key={project.id} {...project} />
      ))}
    </section>
  );
};

export default Projects;
