// src/components/SocialLinks.vue
<template>
  <ul v-if="$static.Links.edges.length" class="socialLinks">
    <li v-for="link in $static.Links.edges"
        :key="link.node.id"
        class="socialLinks__item">
      <a :aria-label="link.node.title"
         :href="link.node.url"
         class="socialLinks__link"
         rel="nofollow noopener"
         target="_blank"
         v-html="link.node.image">
        <span class="sr-only">{{ link.node.title }}</span>
      </a>
    </li>
  </ul>
</template>

<script>
export default {
  name: 'SocialLinks',
};
</script>

<style lang="scss" scoped>
.socialLinks {
  position: fixed;
  top: calc(50% - 120px);
  left: 45px;
  display: none;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  row-gap: 40px;

  &__item {
    width: 30px;
    height: 30px;
  }

  &__link::v-deep {
    @include flex-center;
    width: 100%;
    height: 100%;
    transition: transform var(--transition-duration) var(--transition-timing-function);

    svg {
      width: 20px;
      height: 20px;

      path {
        transition: stroke var(--transition-duration) var(--transition-timing-function);
        stroke: var(--font-color);
      }
    }

    @include hover {
      transform: scale(1.12) translateY(-5px);

      path {
        stroke: var(--third-color);
      }
    }
  }
}

@media screen and (min-width: 768px) {
  .socialLinks {
    display: flex;
  }
}
</style>

<static-query>
query {
  Links: allLinks(sortBy: "id", order: ASC) {
    edges {
      node {
        id
        name
        url
        title
        image
      }
    }
  }
}
</static-query>

// components/social-links.tsx
import cx from "classnames";
import socialLinks from "content/social-links.json";
import React from "react";

type Props = {
  className?: string;
};

const SocialLinks = ({ className }: Props) => {
  return (
    <ul
      className={cx(className, {
        "fixed z-30 hidden left-[35px] top-1/2 -translate-y-1/2 lg:flex flex-col items-center justify-center gap-y-9":
          !className,
      })}>
      {socialLinks.map((link) => (
        <li key={link.id}>
          <a
            aria-label={link.buttonTitle}
            href={link.url}
            className="social-link"
            rel="noreferrer nofollow noopener"
            target="_blank"
            dangerouslySetInnerHTML={{ __html: link.icon }}></a>
        </li>
      ))}
    </ul>
  );
};

export default SocialLinks;
