// pages/404.tsx
import Link from "next/link";
import Layout from "../layouts/layout";

export default function Error404() {
  return (
    <Layout className="relative min-h-inner-screen lg:min-h-inner-screen-lg">
      <section className="absolute z-0 flex flex-col items-center justify-center gap-4 -translate-x-1/2 -translate-y-1/2 left-1/2 top-error lg:top-error-lg">
        <h1 className="text-4xl font-secondary">404</h1>
        <p className="text-center tet-2xl">Strona nie istnieje ¯\_(ツ)_/¯</p>
        <Link href="/" className="button w-max">
          Zabierz mnie stąd!
        </Link>
      </section>
    </Layout>
  );
}

// src/pages/404.vue
<template>
  <Layout>
    <section id="error" class="error">
      <h1 class="sectionHeader">Błąd 404</h1>
        <p class="error--info">Strona nie istnieje ¯\_(ツ)_/¯</p>
    </section>
  </Layout>
</template>

<script>
export default {
  name: '404',
};
</script>

<style lang="scss" scoped>
.error {
  min-height: calc(100vh - 230px);
  padding-top: 180px;

  &--info {
    text-align: center;
    font-size: 32px;
  }
}

@media screen and (min-width: 768px) {
  .error {
    min-height: calc(100vh - 200px);
  }
}
</style>
