// components/header.tsx
"use client";

import { BREAKPOINTS, cn, isMobile } from "helpers";
import { useEffect, useState } from "react";
import useBreakpoint from "use-breakpoint";

export default function Header() {
  const { breakpoint } = useBreakpoint(BREAKPOINTS);
  const [opened, setOpened] = useState(false);

  useEffect(() => {
    const body = document.querySelector("body");
    if (body && opened) body.classList.add("overflow-hidden", "touch-none");
    if (body && !opened) body.classList.remove("overflow-hidden", "touch-none");
    if (!isMobile(breakpoint)) setOpened(false);
  }, [breakpoint, opened]);

  return (
    <header className="absolute inset-x-0 top-0 z-10">
      <nav className="flex items-center justify-between px-5 py-8 lg:px-12">
        <button
          aria-label="Pokaż/Ukryj nawigację serwisu"
          className="relative z-50 w-12 h-9 py-px px-[7px] lg:hidden group"
          onClick={() => setOpened((prevState) => !prevState)}>
          <span
            className={cn(
              "relative w-full h-[3px] block text-center bg-font-dark dark:bg-font-light rounded-sm my-0 mx-auto transition-all duration-1000 before:content-[''] after:content-[''] before:absolute after:absolute before:left-0 after:left-0 before:w-full after:w-full before:h-[3px] after:h-[3px] before:bg-font-dark after:bg-font-dark dark:before:bg-font-light dark:after:bg-font-light before:rounded-sm after:rounded-sm before:transition-all after:transition-all before:duration-1000 after:duration-1000 after:-bottom-[10px] group-hover:bg-accent-light dark:group-hover:bg-accent-dark group-hover:before:bg-accent-light dark:group-hover:before:bg-accent-dark group-hover:after:bg-accent-light dark:group-hover:after:bg-accent-dark",
              {
                "bg-font-dark/0 dark:bg-font-light/0 group-hover:bg-font-dark/0 group-hover:dark:bg-font-light/0 before:top-0 before:rotate-[135deg] after:top-0 after:rotate-[225deg]":
                  opened,
                "before:-top-[10px]": !opened,
              }
            )}></span>
        </button>
        <div
          className={cn(
            "flex-center text-lg md:text-2xl lg:text-base gap-x-4 gap-y-7 md:gap-y-10 lg:gap-y-0 invisible -translate-x-full lg:visible lg:-translate-x-0 fixed lg:static flex-col lg:flex-row bg-secondary-light dark:bg-secondary-dark lg:bg-transparent lg:dark:bg-transparent transition-all duration-700 lg:transition-none h-full lg:h-auto px-5 pt-28 pb-20 lg:px-0 lg:pt-0 lg:pb-0 z-40 top-0 left-0 right-0",
            {
              "!visible !translate-x-0": opened,
            }
          )}>
          <a
            aria-label="Przejdź do sekcji o mnie"
            className="px-4 py-2 text-center font-secondary after:bottom-1 w-max link"
            href="/#o_mnie"
            onClick={() => setOpened(false)}>
            o mnie
          </a>
          <a
            aria-label="Przejdź do sekcji projekty"
            className="px-4 py-2 text-center font-secondary after:bottom-1 w-max link"
            href="/#projekty"
            onClick={() => setOpened(false)}>
            projekty
          </a>
          <a
            aria-label="Przejdź do sekcji kontakt"
            className="px-4 py-2 text-center font-secondary after:bottom-1 w-max link"
            href="/#kontakt"
            onClick={() => setOpened(false)}>
            kontakt
          </a>
        </div>
      </nav>
      <svg
        className="absolute z-30 origin-top -translate-x-1/2 left-1/2 w-logo top-logo"
        fill="none"
        height="113"
        viewBox="0 0 93 113"
        width="93"
        xmlns="http://www.w3.org/2000/svg">
        <title>Logo serwisu jakubsoboczynski.pl</title>
        <path
          className="transition-colors stroke-font-dark dark:stroke-font-light"
          d="M46.7376 104.089V112M46.7376 112H38.0787L24.3421 91.3683L2 73.516L10.6055 56.5724M46.7376 112H55.2896L69.0262 91.3683L91.3683 73.516L82.7629 56.5724M10.6055 56.5724L8.89505 2L10.6055 2.05345L38.0787 30.0078M10.6055 56.5724L38.0787 30.0078M10.6055 56.5724L46.7376 78.1127M82.7629 56.5724L46.7376 78.1127M82.7629 56.5724L84.4733 2.00001H82.7629L55.2896 30.0078M82.7629 56.5724L55.2896 30.0078M38.0787 30.0078H46.7376M46.7376 78.1127L55.436 51.9757M46.7376 78.1127L38.0569 52.0292M46.7376 30.0078L35.5666 44.5462L38.0569 52.0292M46.7376 30.0078L57.9086 44.5462L55.436 51.9757M46.7376 30.0078H55.2896M55.436 51.9757L46.7376 40.6978L38.0569 52.0292M66.1399 66.4072H74.0505L67.5296 72.1263L54.274 73.8902L65.1778 67.1555M27.5491 66.4072H19.6385L26.1594 72.1263L39.415 73.8902L28.5112 67.1555L27.5491 66.4072Z"
          stroke="white"
          strokeWidth="2"
        />
      </svg>
    </header>
  );
}

// src/components/Header.vue
<template>
  <header class="header">
    <nav class="nav">
      <button v-show="$route.name === 'home'"
              aria-label="Pokaż/Ukryj nawigację"
              class="nav__burger"
              @click="toggleMenu"><span></span></button>
      <div v-show="$route.name === 'home'" class="nav__wrapper">
        <a v-smooth-scroll
           aria-label="Przejdź do sekcji o mnie"
           class="nav__link link"
           href="#o_mnie"
           @click="hideMenu">o
          mnie
        </a>
        <a v-smooth-scroll
           aria-label="Przejdź do sekcji projekty"
           class="nav__link link"
           href="#projekty"
           @click="hideMenu">
          projekty
        </a>
        <a v-smooth-scroll
           aria-label="Przejdź do sekcji kontakt"
           class="nav__link link"
           href="#kontakt"
           @click="hideMenu">
          kontakt
        </a>
      </div>
      <g-link :aria-label="$route.name === 'home' ? 'Przejdź do podstrony zawierającej blog' : 'Przejdź do portfolio'"
              :to="$route.name === 'home' ? '/blog/' : '/'"
              class="button">
        {{ $route.name === 'home' ? 'Blog' : 'Portfolio' }}
      </g-link>
    </nav>
    <svg class="header__logo"
         fill="none"
         height="113"
         viewBox="0 0 93 113"
         width="93"
         xmlns="http://www.w3.org/2000/svg">
      <title>Logo serwisu jakubsoboczynski.pl</title>
      <path d="M46.7376 104.089V112M46.7376 112H38.0787L24.3421 91.3683L2 73.516L10.6055 56.5724M46.7376 112H55.2896L69.0262 91.3683L91.3683 73.516L82.7629 56.5724M10.6055 56.5724L8.89505 2L10.6055 2.05345L38.0787 30.0078M10.6055 56.5724L38.0787 30.0078M10.6055 56.5724L46.7376 78.1127M82.7629 56.5724L46.7376 78.1127M82.7629 56.5724L84.4733 2.00001H82.7629L55.2896 30.0078M82.7629 56.5724L55.2896 30.0078M38.0787 30.0078H46.7376M46.7376 78.1127L55.436 51.9757M46.7376 78.1127L38.0569 52.0292M46.7376 30.0078L35.5666 44.5462L38.0569 52.0292M46.7376 30.0078L57.9086 44.5462L55.436 51.9757M46.7376 30.0078H55.2896M55.436 51.9757L46.7376 40.6978L38.0569 52.0292M66.1399 66.4072H74.0505L67.5296 72.1263L54.274 73.8902L65.1778 67.1555M27.5491 66.4072H19.6385L26.1594 72.1263L39.415 73.8902L28.5112 67.1555L27.5491 66.4072Z"
            stroke="white"
            stroke-width="2" />
    </svg>
  </header>
</template>

<script>
export default {
  name: 'Header',
  methods: {
    detectMobile() {
      const width = (window.innerWidth > 0) ? window.innerWidth : document.documentElement.clientWidth;
      const nav = document.querySelector('.nav__wrapper');
      if (width > 768) {
        nav.classList.remove('mobile');
        this.hideMenu();
      } else {
        nav.classList.add('mobile');
      }
    },
    toggleMenu() {
      document.querySelector('.nav__wrapper').classList.toggle('opened');
      document.querySelector('.nav__burger').classList.toggle('opened');
      document.querySelector('body').classList.toggle('opened');
    },
    hideMenu() {
      document.querySelector('.nav__wrapper').classList.remove('opened');
      document.querySelector('.nav__burger').classList.remove('opened');
      document.querySelector('body').removeAttribute('class');
    },
  },
  mounted() {
    this.detectMobile();
    window.addEventListener('resize', this.detectMobile);
  },
};
</script>

<style lang="scss" scoped>
.header {
  position: absolute;
  z-index: 1;
  top: 0;
  right: 0;
  left: 0;

  .nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 40px 20px;

    &__burger {
      position: relative;
      z-index: 5;
      width: 48px;
      height: 38px;

      @include hover {
        span,
        span:before,
        span:after {
          background-color: var(--third-color);
        }
      }

      span {
        position: relative;
        width: 100%;
        height: 3px;
        display: block;
        text-align: center;
        background-color: var(--font-color);
        border-radius: 3px;
        margin: 0 auto;
        transition: background 2s var(--transition-timing-function);

        &:before,
        &:after {
          content: '';
          position: absolute;
          left: 0;
          width: 100%;
          height: 3px;
          background-color: var(--font-color);
          border-radius: 3px;
        }

        &:before {
          top: -10px;
          transition-timing-function: var(--transition-timing-function);
          transition-duration: 2s;
          transition-property: background, top, box-shadow, transform;
        }

        &:after {
          bottom: -10px;
          transition-timing-function: var(--transition-timing-function);
          transition-duration: 2s;
          transition-property: background, bottom, box-shadow, transform;
        }
      }

      &.opened {
        span {
          background: rgba(var(--font-color-rgb), 0);

          &:before {
            top: 0;
            box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.2);
            transform: rotate(135deg);
          }

          &:after {
            top: 0;
            box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.2);
            transform: rotate(225deg);
          }
        }
      }
    }

    &__wrapper {
      position: fixed;
      z-index: 2;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      visibility: hidden;
      font-size: 24px;
      background-color: var(--secondary-color);
      padding: 120px 20px 80px;
      transform: translateX(-100%);
      row-gap: 30px;

      &.opened {
        visibility: visible;
        transform: translateX(0);
      }

      &.mobile {
        transition-timing-function: var(--transition-timing-function);
        transition-duration: 0.75s;
        transition-property: transform, visibility, background;
      }
    }

    &__link {
      width: max-content;
      font-family: var(--font-family-secondary);
      padding: 10px 15px;

      &:after {
        bottom: 5px;
        width: calc(80% - 30px);
      }
    }
  }

  &__logo {
    position: absolute;
    top: clamp(0.9375rem, 0.50304867rem + 1.853659vw, 2.125rem);
    left: 50%;
    width: clamp(4.375rem, 3.68902445rem + 2.926829vw, 6.25rem);
    transform: translateX(-50%);
    transform-origin: top;

    path {
      transition: stroke var(--transition-duration) var(--transition-timing-function);
      stroke: var(--font-color);
    }
  }
}

@media screen and (min-width: 768px) {
  .header {
    .nav {
      padding: 40px 50px;

      &__burger {
        display: none;
      }

      &__wrapper {
        position: static;
        width: unset;
        height: unset;
        flex-direction: row;
        visibility: visible;
        font-size: 16px;
        background: none;
        padding: 0;
        transform: translateX(0);
        row-gap: unset;
        column-gap: 15px;
      }

      &__link {
        font-family: var(--font-family-secondary);
      }
    }
  }
}
</style>
