// src/pages/Index.vue
<template>
  <Layout>
    <Hero />
    <AboutMe :aboutMe="$page.aboutMe.edges" />
    <Projects :projects="$page.projects.edges" />
    <Contact :contact="$page.contact.edges" />
  </Layout>
</template>

<script>
import Hero from '~/views/Hero.vue';
import AboutMe from '~/views/AboutMe.vue';
import Projects from '~/views/Projects.vue';
import Contact from '~/views/Contact.vue';

export default {
  name: 'Homepage',
  metaInfo: {
    title: 'Hello!',
  },
  components: {
    Hero,
    AboutMe,
    Projects,
    Contact,
  },
};
</script>

<!--language=GRAPHQL-->
<page-query>
query {
  aboutMe: allAboutMe(sortBy: "id", order: ASC) {
    edges {
      node {
        id
        title
        description
      }
    }
  }
  projects: allProjects(sortBy: "id", order: ASC) {
    edges {
      node {
        id
        title
        description
        technologies
        source
        demo
        image {
          url
        }
        imageAlt
      }
    }
  }
  contact: allContact {
    edges {
      node {
        id
        description
      }
    }
  }
}
</page-query>

// pages/index.tsx
import Meta from "components/seo-meta";
import Layout from "layouts/layout";
import AboutMe from "../views/about-me";
import Contact from "../views/contact";
import Hero from "../views/hero";
import Projects from "../views/projects";

export default function Home() {
  return (
    <>
      <Meta title="Hello!" description="My own page." />
      <Layout>
        <Hero />
        <AboutMe />
        <Projects />
        <Contact />
      </Layout>
    </>
  );
}
